<div id="banner_interior">
	<img src="/img/avisodeprivacidad_banner.png" alt="Dudas">
	<div class="divider"></div>
</div>
<div id="preguntas_contenido">
	<p>En MetLife estamos comprometidos a protegerte a ti y a tus seres queridos. Como parte de esta protección, te informamos que los datos personales que nos proporcionas son tratados con absoluta confidencialidad y que contamos con las medidas de seguridad suficientes para garantizar la protección de tus datos personales en apego a la Ley Federal de Protección de Datos Personales en Posesión de los Particulares. Por ello, ponemos a tu disposición nuestro Aviso de Privacidad.</p>
	<p>I. IDENTIDAD Y DOMICILIO DEL RESPONSABLE QUE RECABA LOS DATOS.<br>MetLife México, S.A., ubicada en Boulevard Manuel Ávila Camacho No. 32, pisos skl, 14 al 20 y PH, Col. Lomas de Chapultepec, Deleg. Miguel Hidalgo, C.P. 11000, México, D.F.</p>
	<p>II. FINALIDADES DEL TRATAMIENTO DE DATOS.<br>Los datos personales que recabamos directamente de ti, de otras fuentes permitidas por la ley o los que se generen de estas o de la relación que lleguemos a establecer, los utilizamos para inscribirte en nuestros cursos, registrarte en nuestro programa de incentivos o recompensas, coordinar los eventos en los que participas con nosotros, enviarte información y  confirmaciones de nuestros eventos, darle seguimiento a cambios en tus reservaciones, emitir tus boletos de avión, reservar tu habitación, evaluar nuestros eventos; y para fines secundarios al promocionarte nuestros productos o servicios financieros o de nuestras filiales, subsidiarias y partes relacionadas o al realizar campañas publicitarias o con fines de mercadotecnia. Para estas finalidades requerimos tus datos de personales como datos de identificación y datos migratorios, como nombre, fecha de nacimiento, nacionalidad, pasaporte, visa, dirección, teléfono(s), datos de tu acompañante y de contacto en caso de emergencia, tipo de dieta; y tus datos personales sensibles de salud como tipo de sangre, alergias. Adicionalmente recabamos datos que no son personales, como tu línea de negocio, promotoria, sucursal, tipo de habitación, elección de actividades en los eventos; los cuales utilizamos para conocer el número de participantes en nuestros eventos, programas o cursos por línea de negocio o por promotoria.</p>
	<p>III. OPCIONES Y MEDIOS PARA LIMITAR EL USO O DIVULGACIÓN DE TUS DATOS PERSONALES.<br>Si deseas que tus datos no sean tratados con fines secundarios, al promocionarte productos o servicios financieros, te pedimos llenar el siguiente formulario Preferencias de Privacidad de esta hoja electrónica y te pedimos leer cuidadosamente las Reglas sobre preferencias de privacidad en donde se señalan los detalles sobre los términos y el alcance de la solicitud; también puedes inscribirte en el Registro Público de Usuarios (Reus) a cargo de la Condusef, para ello puedes visitar su página de Internet o contactarla directamente.<br>Si este aviso de privacidad no se te da a conocer de manera directa o personal, tienes un plazo de 5 días para oponerte al tratamiento y transferencia de tus datos para los fines secundarios indicados, utilizando los mismos medios mencionados anteriormente.</p>
	<p>IV. MEDIOS PARA EJERCER TUS DERECHOS Y REVOCAR TU CONSENTIMIENTO.<br>Tienes derecho a acceder, rectificar, cancelar y oponerte al tratamiento de tus datos o puedes revocar el consentimiento que nos hayas otorgado solicitándolo personalmente en nuestro departamento de protección de datos en la dirección arriba citada, en nuestros Centros de Servicios, que puedes ubicar en este sitio de internet, o enviando un correo a contacto@metlife.com.mx acompañando a dicha solicitud lo siguiente:</p>
	<p>a) Tu nombre completo como titular de los datos y correo electrónico, domicilio  u otro medio para que te comuniquemos la  respuesta a tu solicitud;<br>b) Los documentos que acrediten tu identidad o, en su caso, a la de tu representante legal;<br>c) La descripción clara y precisa de los datos personales respecto de los que buscas ejercer alguno de los derechos antes mencionados, y<br>d) Cualquier otro elemento o documento que facilite la localización de tus datos personales.</p>
	<p>En el caso de solicitudes de rectificación de datos personales, deberás indicar, además de lo señalado anteriormente, las modificaciones a realizarse y aportar la documentación que sustente tu petición.<br>MetLife te comunicará, en un plazo máximo de veinte días hábiles, contados desde la fecha en que se recibió tu solicitud, la determinación adoptada, a efecto de que, si resulta procedente, se haga efectiva la misma dentro de los quince días hábiles siguientes a la fecha en que te comunica la respuesta. Tratándose de solicitudes de acceso a datos personales, procederá la entrega previa acreditación de la identidad del solicitante o representante legal, según corresponda.</p>
	<p>Los plazos antes referidos podrán ser ampliados una sola vez por un periodo igual, siempre y cuando así lo justifiquen las circunstancias del caso.</p>
	<p>La obligación de acceso a tu información se dará por cumplida cuando se pongan a tu disposición los datos personales; o bien, mediante la expedición de copias simples, documentos electrónicos o cualquier otro medio.</p>
	<p>MetLife podrá negarte el acceso a los datos personales, o a realizar la rectificación o cancelación o conceder la oposición al tratamiento de los mismos, en los siguientes casos:</p>
	<p>I. Si eres el solicitante, pero no el titular de los datos personales, o tu representante legal no esté debidamente acreditado para ello;<br>II. Cuando en nuestra base de datos, no se encuentren tus datos personales;<br>III. Cuando se lesionen los derechos de un tercero;<br>IV. Cuando exista un impedimento legal, o la resolución de una autoridad competente, que restrinja el acceso a tus datos personales, o no permita la rectificación, cancelación u oposición de los mismos, y<br>V. Cuando la rectificación, cancelación u oposición haya sido previamente realizada.</p>
	<p>En todos los casos anteriores, te informaremos el motivo de nuestra decisión y te la comunicaremos, o en su caso, a tu representante legal, en los plazos establecidos para tal efecto, por el mismo medio por el que se llevó a cabo la solicitud, acompañando, en su caso, las pruebas que resulten pertinentes.</p>
	<p>V. TRANSFERENCIA DE DATOS. <br>Podemos transferir tus datos a terceros nacionales o internacionales como dependencias, entidades o instancias gubernamentales para fines de Ley o por requerimiento de Autoridad; a American Express para la coordinación de nuestros eventos; y a nuestras subsidiarias, filiales y partes relacionadas para fines de mercadotecnia, publicidad o prospección comercial.</p>
	<p>VI. CAMBIOS AL AVISO DE PRIVACIDAD.<br>Los cambios o actualizaciones a este aviso de privacidad están disponibles y puedes consultarlos periódicamente en este sitio de internet. Este aviso se fundamenta en lo dispuesto en la Ley Federal de Protección de Datos Personales en Posesión de los Particulares y demás legislación aplicable.</p>
	<p>COOKIES<br>La cookie es una breve información que el portal de Internet envía a tu computadora, la cual queda almacenada en el disco duro. La próxima vez que ingreses a nuestro portal, podremos usar la información almacenada en la cookie para facilitarte el uso de nuestro sitio de Internet. Por ejemplo, podemos usar tu cookie para almacenar una contraseña para que no tengas que ingresarla de nuevo cada vez que te traslades a una sección diferente de nuestro portal de Internet. Una cookie no nos permite conocer tu identidad personal a menos que expresamente elijas proporcionárnosla. La mayoría de las cookies expiran después de un periodo determinado de tiempo, o bien las puedes borrar en el momento en que lo desees siguiendo las instrucciones de su navegador de Internet. Asimismo, puedes hacer que tu navegador te avise cuando recibes una cookie de manera que puedas aceptarlas o rechazarlas siguiendo las instrucciones de su navegador de Internet.</p>
	<p>FECHA DE LA ÚLTIMA ACTUALIZACIÓN: Mayo, 2014</p>
</div>